import { VectorUIRoot } from "../../components/VectorUIRoot";
import { Card } from "../../components/Card";
import { LandscapeCard } from "../../components/LandscapeCard";
import { scoopCard, triangleFloat, wobbleEdge } from "../../shapes";
import { Pill } from "../../components/Pill";
import { tokens } from "../..";

/**
 * Demo 2 — `Card`: a shape-as-container core component.
 *
 * Both versions exercise the SAME core component, `<Card>`. Card takes a
 * `shape` (any `ShapeGenerator`) and renders a header / body / actions stack
 * whose content auto-follows the shape's boundary — body text reflows to the
 * contour, rigid widgets land in a derived safe rectangle. Card itself knows
 * nothing about any specific shape family.
 *
 *   Version A — `<Card shape={scoopCard(...)}>`: a scoop is carved into the
 *   left edge; the body paragraph hugs the curve, then squares off below.
 *   We pass the FULL bundle (`{ path, flowAround }`), not just `.path`, so
 *   Card's shape-fit slot consumes the closed-form intrusion and skips
 *   per-frame contour sampling. Bundle vs. plain `.path` is the difference
 *   between ~50 ms and ~2.4 s on first paint.
 *
 *   Version B — `<LandscapeCard>` is a thin wrapper over the same `Card`,
 *   pointing its `body` at a `<WrapText>` with a `<Float>`. The Float draws
 *   an inner feature shape (a triangle), holds the title text inside it, AND
 *   the surrounding body wraps around it — three jobs from one path. No
 *   bespoke Frame slots; no per-shape intrusion. Look at `LandscapeCard.tsx`
 *   in the Code tab: it's about twenty lines of composition.
 *
 * All shapes are constructed in this file and passed as props — so swapping
 * `scoopCard` for `cornerBlob`, or the triangle for an arch, is a one-line
 * change at the call site.
 *
 * Note on animation: Card has no built-in animation. A consumer can morph the
 * shape today by re-rendering with a new path per frame, but a dedicated
 * `<MorphPath>` primitive that animates the `d` attribute via a ref (no React
 * re-render) is a future addition. Both cards here are static so the
 * shape-as-prop + contour-fit primitives speak for themselves.
 */

const BODY_A =
  "The card's left edge is not straight: a smooth scoop is carved out of it, and this paragraph is poured to follow that exact curve. The lines step inward as the scoop deepens, then square off below it. The very same function generates the drawn outline and the wrap profile, so the text hugs the contour that is rendered — not an approximation of it. The shape is constructed in demo.tsx (a scoopCard) and passed to Card as a prop; Card itself knows nothing about scoops.";

const BODY_B =
  "The dark triangle to the left is the title's frame, and the wobbly slope of its right side dictates exactly how far this paragraph indents on each line. The first lines hug the peak closely, then step further inward as the slope flares to the base — every bend of the hand-drawn contour pushes a line by precisely that amount. Below the triangle the column squares back off to the card's full width. The path and the wrap profile are generated by the same function, so the text follows the rendered contour rather than an approximation of it. The four outer edges of the card carry their own (gentler) wobble — this whole postcard is one SVG, no <img>, no <hr>, no <div>.";

const ROOT_WIDTH = 520;
const MARGIN = 56;

// ---- Version A: scoop shape built here, passed as a prop ----

// Pass the FULL bundle (path + closed-form flowAround), not just `.path`.
// That lets Card's shape-fit slot consume the analytical intrusion and skip
// per-band contour sampling — which is the difference between ~1ms and
// ~115ms per layout settle iteration. With a 20-frame settle loop, that's
// 2 seconds vs 20ms.
const scoopShape = scoopCard({
  cornerRadius: 22,
  scoopTop: 64,
  scoopHeight: 150,
  depth: 104,
});

// ---- Version B: outer card + inner triangle, both built here, both as props ----

const TRI_W = 220;
const TRI_H = 175;
const CARD_WOBBLE = 12;
const TRIANGLE_WOBBLE = 22;

const round = (n: number) => Math.round(n * 100) / 100;

/** Hand-drawn rectangular outline with wobbly edges. */
function wobblyRect(w: number, h: number): string {
  const cr = Math.min(w, h) * 0.025;
  const p = round;
  const d: string[] = [`M ${p(cr)} 0`];
  wobbleEdge(d, cr, 0, w - cr, 0, CARD_WOBBLE, 0.4);
  d.push(`Q ${p(w)} 0 ${p(w)} ${p(cr)}`);
  wobbleEdge(d, w, cr, w, h - cr, CARD_WOBBLE, 1.8);
  d.push(`Q ${p(w)} ${p(h)} ${p(w - cr)} ${p(h)}`);
  wobbleEdge(d, w - cr, h, cr, h, CARD_WOBBLE, 3.1);
  d.push(`Q 0 ${p(h)} 0 ${p(h - cr)}`);
  wobbleEdge(d, 0, h - cr, 0, cr, CARD_WOBBLE, 4.6);
  d.push(`Q 0 0 ${p(cr)} 0`, "Z");
  return d.join(" ");
}

const triangle = (_w: number, _h: number) =>
  triangleFloat({ width: TRI_W, height: TRI_H, wobble: TRIANGLE_WOBBLE }).path;

export function Demo() {
  return (
    <div>
      <p style={{ color: "#555", maxWidth: 640 }}>
        Both versions are the library's core <code>Card</code> component —
        a shape-as-container with a header / body / actions stack whose
        content auto-follows the boundary. <code>Card</code> takes a{" "}
        <code>shape</code> prop (any path generator); the body text reflows
        to the contour, and rigid widgets land in a derived safe rectangle.
        Card knows nothing about any specific shape family — swapping a
        scoop for a blob, or a triangle for an arch, is a one-line change at
        the call site.
      </p>
      <p style={{ color: "#555", maxWidth: 640 }}>
        <strong>Version A</strong> is{" "}
        <code>&lt;Card shape={"{"}scoopCard(...){"}"}/&gt;</code> — passing
        the full <code>{`{ path, flowAround }`}</code> bundle — with a scoop
        carved into the left edge. <strong>Version B</strong> —{" "}
        <code>LandscapeCard</code> — is itself a thin wrapper over the same{" "}
        <code>Card</code>, pointing its <code>body</code> at a{" "}
        <code>&lt;WrapText&gt;</code> with a <code>&lt;Float&gt;</code> that
        does three jobs from one path: draws an inner triangle, holds the
        title inside it, and lets the body wrap around it. See the Code tab
        for both compositions.
      </p>

      <p className="variant-label">
        Version A — <code>Card</code> with a scoop-edge shape
      </p>
      <VectorUIRoot
        padding={MARGIN}
        style={{ maxWidth: ROOT_WIDTH, background: "#f0efe9" }}
      >
        <Card
          shape={scoopShape}
          width={400}
          title="Text follows the path"
          body={BODY_A}
          actions={
            <Pill
              role="button"
              tabIndex={0}
              style={{ cursor: "pointer" }}
              textStyle={tokens.type.label}
              height={34}
              paddingX={18}
            >
              Got it
            </Pill>
          }
        />
      </VectorUIRoot>

      <p className="variant-label">
        Version B — <code>LandscapeCard</code>: the same <code>Card</code>,
        with a Float-as-feature body
      </p>
      <VectorUIRoot
        padding={MARGIN}
        style={{ maxWidth: ROOT_WIDTH, background: "#e8e3d3" }}
      >
        <LandscapeCard
          outline={wobblyRect}
          feature={triangle}
          featureWidth={TRI_W}
          featureHeight={TRI_H}
          width={400}
          title="A spooky wobbly title that follows the path"
          body={BODY_B}
          surface="#f3ecde"
          featureFill="#243029"
          titleFill="#f3ecde"
          bodyFill="#3d4540"
        />
      </VectorUIRoot>
    </div>
  );
}
