import { VectorUIRoot } from "../../components/VectorUIRoot";
import { Flow } from "../../components/Flow";
import { Card } from "../../components/Card";
import { LandscapeCard } from "../../components/LandscapeCard";
import { scoopCard, triangleFloat, wobbleEdge } from "../../shapes";
import { Button } from "./Button";

/**
 * Demo 2 — non-rectangular card (SPEC §11).
 *
 * Both cards are now the library's reusable components — `<Card>` and
 * `<LandscapeCard>` — and the SHAPES are constructed here in `demo.tsx` and
 * passed as props. Card knows nothing about scoops; LandscapeCard knows
 * nothing about triangles. The body/title text auto-follow whatever boundary
 * the demo passes in, because Frame's `shape-fit` slots derive the contour
 * from the path via the occupancy engine.
 *
 * Version A constructs a `scoopCard` and passes its path to `<Card shape={...}>`.
 * Version B constructs a wobbly rect for the outer card and a `triangleFloat`
 * for the inner feature.
 *
 * Proves: Frame as a shape-container with contour-fit slots; arbitrary shape
 * passed in; rigid widgets in a derived safe rectangle.
 *
 * Note on animation: Card has no built-in animation — it just renders whatever
 * `shape` you hand it. A consumer can morph the shape by re-rendering with a
 * new path per frame (e.g., a hover-driven `scoopCard` morph wired via
 * `useState` + `useTween`), but that re-renders the whole subtree each tick;
 * a dedicated `<MorphPath>` primitive that animates the `d` attribute via a
 * ref (no React re-render) is a future addition. For this demo, both cards
 * are static so the shape-as-prop + contour-fit primitives speak for themselves.
 */

const BODY_A =
  "The card's left edge is not straight: a smooth scoop is carved out of it, and this paragraph is poured to follow that exact curve. The lines step inward as the scoop deepens, then square off below it. The very same function generates the drawn outline and the wrap profile, so the text hugs the contour that is rendered — not an approximation of it. The shape is constructed in demo.tsx (a scoopCard) and passed to Card as a prop; Card itself knows nothing about scoops.";

const BODY_B =
  "The dark triangle to the left is the title's frame, and the wobbly slope of its right side dictates exactly how far this paragraph indents on each line. The first lines hug the peak closely, then step further inward as the slope flares to the base — every bend of the hand-drawn contour pushes a line by precisely that amount. Below the triangle the column squares back off to the card's full width. The path and the wrap profile are generated by the same function, so the text follows the rendered contour rather than an approximation of it. The four outer edges of the card carry their own (gentler) wobble — this whole postcard is one SVG, no <img>, no <hr>, no <div>.";

const ROOT_WIDTH = 520;
const MARGIN = 56;

// ---- Version A: scoop shape built here, passed as a prop ----

const scoopShape = scoopCard({
  cornerRadius: 22,
  scoopTop: 64,
  scoopHeight: 150,
  depth: 104,
}).path;

// ---- Version B: outer card + inner triangle, both built here, both as props ----

const TRI_W = 220;
const TRI_H = 175;
const CARD_WOBBLE = 12;
const TRIANGLE_WOBBLE = 22;

const round = (n: number) => Math.round(n * 100) / 100;

/** Hand-drawn rectangular outline with wobbly edges. */
function wobblyRect(w: number, h: number): string {
  const cr = Math.min(w, h) * 0.025;
  const p = round;
  const d: string[] = [`M ${p(cr)} 0`];
  wobbleEdge(d, cr, 0, w - cr, 0, CARD_WOBBLE, 0.4);
  d.push(`Q ${p(w)} 0 ${p(w)} ${p(cr)}`);
  wobbleEdge(d, w, cr, w, h - cr, CARD_WOBBLE, 1.8);
  d.push(`Q ${p(w)} ${p(h)} ${p(w - cr)} ${p(h)}`);
  wobbleEdge(d, w - cr, h, cr, h, CARD_WOBBLE, 3.1);
  d.push(`Q 0 ${p(h)} 0 ${p(h - cr)}`);
  wobbleEdge(d, 0, h - cr, 0, cr, CARD_WOBBLE, 4.6);
  d.push(`Q 0 0 ${p(cr)} 0`, "Z");
  return d.join(" ");
}

const triangle = (_w: number, _h: number) =>
  triangleFloat({ width: TRI_W, height: TRI_H, wobble: TRIANGLE_WOBBLE }).path;

export function Demo() {
  return (
    <div>
      <p style={{ color: "#555", maxWidth: 640 }}>
        Two cards, each a generated path. <strong>Version A</strong> carves a
        scoop into its left edge and pours the body around it.{" "}
        <strong>Version B</strong> is a hand-drawn postcard whose title sits
        inside a triangle, with the body text wrapping the triangle's wobbly
        right slope. Both cards are the library's reusable{" "}
        <code>Card</code> / <code>LandscapeCard</code>; the shapes are
        constructed here in <code>demo.tsx</code> and passed as props.
      </p>

      <p className="variant-label">
        Version A — scoop edge: body text auto-wraps the scoop
      </p>
      <VectorUIRoot
        width={ROOT_WIDTH}
        height="content"
        style={{ maxWidth: ROOT_WIDTH, background: "#f0efe9" }}
      >
        <Flow
          padding={MARGIN}
          align="center"
          crossSize={ROOT_WIDTH - MARGIN * 2}
        >
          <Card
            shape={scoopShape}
            width={400}
            title="Text follows the path"
            body={BODY_A}
            actions={<Button>Got it</Button>}
          />
        </Flow>
      </VectorUIRoot>

      <p className="variant-label">
        Version B — hand-drawn postcard, title in a triangle, body wraps its
        slope
      </p>
      <VectorUIRoot
        width={ROOT_WIDTH}
        height="content"
        style={{ maxWidth: ROOT_WIDTH, background: "#e8e3d3" }}
      >
        <Flow
          padding={MARGIN}
          align="center"
          crossSize={ROOT_WIDTH - MARGIN * 2}
        >
          <LandscapeCard
            outline={wobblyRect}
            feature={triangle}
            featureWidth={TRI_W}
            featureHeight={TRI_H}
            width={400}
            title="A spooky wobbly title that follows the path"
            body={BODY_B}
            surface="#f3ecde"
            featureFill="#243029"
            titleFill="#f3ecde"
            bodyFill="#3d4540"
          />
        </Flow>
      </VectorUIRoot>
    </div>
  );
}
