import { useMemo } from "react";
import { Frame } from "../../components/Frame";
import { Text } from "../../components/Text";
import { Pill } from "../../components/Pill";
import { tokens } from "../../tokens";
import { makeFlow, makeShape, type ShapeParams } from "./proceduralShape";

/**
 * The reusable scene: a Frame whose closed path is procedurally generated
 * (left edge waves inward, right edge optionally mirrors), with a centered
 * title Pill at the top and a body Text that reflows around the live left
 * edge via the matching `flowAround.intrusionAt`.
 */

/** Vertical offset, in layout units, of the body text inside the Frame. */
const TITLE_BAND = 56;
/** Fixed left inset of the body slot. Wave intrusions beyond this start
 *  eating into the text column — that is the whole point of the demo. */
const TEXT_LEFT = tokens.space.lg;
/** Right inset of the body slot. */
const PAD_RIGHT = tokens.space.xl;
/** Bottom inset below the body's measured height. */
const PAD_BOTTOM = tokens.space.xl;
/** Gap between the wave's edge and the wrapped text. */
const FLOW_GAP = tokens.space.sm;

const BODY =
  "The left edge of this card is generated by a single closed-form function — amplitude, frequency, phase. The same function answers Text's intrusionAt query, so every line you are reading wraps the exact contour the path draws. Move the sliders: the silhouette morphs and the paragraph reflows around it on one frame, with no manual layout pass in between.";

export type ProceduralPathProps = {
  params: ShapeParams;
  /** Frame width in layout units; matches the wrapper's pixel width so the
   *  `width="auto"` SVG renders at 1:1 (scale = 1). */
  width: number;
};

export function ProceduralPath({ params, width }: ProceduralPathProps) {
  const shape = useMemo(() => makeShape(params), [params]);
  const flowAround = useMemo(
    () => makeFlow(params, TITLE_BAND, TEXT_LEFT, FLOW_GAP),
    [params],
  );

  return (
    <Frame
      shape={shape}
      width={width}
      height="auto"
      padding={PAD_BOTTOM}
      fill={tokens.color.surface}
      stroke={tokens.color.line}
      strokeWidth={1.5}
      title="Procedural path with live text reflow"
      slots={{
        title: {
          type: "anchor",
          x: width / 2,
          y: tokens.space.lg,
          align: "top-center",
        },
        body: {
          type: "region",
          x: TEXT_LEFT,
          y: TITLE_BAND,
          width: Math.max(0, width - TEXT_LEFT - PAD_RIGHT),
          height: "content",
        },
      }}
    >
      <Frame.Slot name="title">
        <Pill textStyle={tokens.type.label} height={28}>
          Procedural shape
        </Pill>
      </Frame.Slot>
      <Frame.Slot name="body">
        <Text
          {...tokens.type.body}
          maxWidth="100%"
          fill={tokens.color.ink}
          flowAround={flowAround}
        >
          {BODY}
        </Text>
      </Frame.Slot>
    </Frame>
  );
}
